cameras:
  - id: CAM-01
    env_uri: CAM_01_URI
    uri: rtsp://192.168.1.210:554/Streaming/Channels/101
  - id: CAM-02
    env_uri: CAM_02_URI
    uri: rtsp://192.168.1.210:554/Streaming/Channels/201
  - id: CAM-03
    env_uri: CAM_03_URI
    uri: rtsp://192.168.1.210:554/Streaming/Channels/301
  - id: CAM-04
    env_uri: CAM_04_URI
    uri: rtsp://192.168.1.210:554/Streaming/Channels/601
  - id: CAM-05
    env_uri: CAM_05_URI
    uri: rtsp://192.168.1.210:554/Streaming/Channels/501
  - id: CAM-06
    env_uri: CAM_06_URI
    uri: rtsp://192.168.1.210:554/Streaming/Channels/401

deepstream:
  gpu_id: 0
  rtsp_transport: auto
  latency_ms: 150
  drop_on_latency: true
  decoder_extra_surfaces: 4
  cudadec_memtype: 0
  udp_buffer_size: 1048576
  reconnect_interval_sec: 2
  reconnect_attempts: -1
  postdecode_queue_buffers: 1
  capture_timeout_ms: 1000
  startup_grace_sec: 8.0
  reconnect_delay_sec: 1.0
  startup_stagger_sec: 0.20

display:
  width: 736
  height: 416
  fps: 20
  jpeg_quality: 70
