#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"

export CAMERA_V2_RTSP_TRANSPORT="${CAMERA_V2_RTSP_TRANSPORT:-tcp}"
export CAMERA_V2_RTSP_LATENCY_MS="${CAMERA_V2_RTSP_LATENCY_MS:-100}"
export CAMERA_V2_SOURCE_FPS="${CAMERA_V2_SOURCE_FPS:-20}"
export CAMERA_V2_EXTRA_SURFACES="${CAMERA_V2_EXTRA_SURFACES:-6}"
export CAMERA_V2_FRAME_WIDTH="${CAMERA_V2_FRAME_WIDTH:-1280}"
export CAMERA_V2_FRAME_HEIGHT="${CAMERA_V2_FRAME_HEIGHT:-720}"
export CAMERA_V2_WALL_WIDTH="${CAMERA_V2_WALL_WIDTH:-1920}"
export CAMERA_V2_WALL_HEIGHT="${CAMERA_V2_WALL_HEIGHT:-720}"
export CAMERA_V2_MUX_TIMEOUT_US="${CAMERA_V2_MUX_TIMEOUT_US:-50000}"
export CAMERA_V2_STARTUP_STAGGER_SEC="${CAMERA_V2_STARTUP_STAGGER_SEC:-0.50}"
export CAMERA_V2_DETECTION_ONLY_STALL_SEC="${CAMERA_V2_DETECTION_ONLY_STALL_SEC:-12}"

# Keep normal sparse detection running so source/display behavior matches the
# current detection-only pipeline. The extra high-res branch is one-shot only.
export CAMERA_V2_DETECT_WIDTH=672
export CAMERA_V2_DETECT_HEIGHT=384
export CAMERA_V2_MICRO_BATCH=1
export CAMERA_V2_DETECT_ACTIVE_CAMERAS="${CAMERA_V2_DETECT_ACTIVE_CAMERAS:-CAM-01,CAM-02,CAM-03,CAM-04,CAM-05,CAM-06}"
export CAMERA_V2_DETECT_CONF="${CAMERA_V2_DETECT_CONF:-0.08}"
export CAMERA_V2_MAX_DET="${CAMERA_V2_MAX_DET:-40}"
export CAMERA_V2_DETECT_TARGET_HZ="${CAMERA_V2_DETECT_TARGET_HZ:-0.33}"
export CAMERA_V2_MAX_DETECT_RESULT_AGE_MS="${CAMERA_V2_MAX_DETECT_RESULT_AGE_MS:-600}"

export CAMERA_V2_POSE_GATE_MODEL="${CAMERA_V2_POSE_GATE_MODEL:-yolo26s-pose.pt}"
export CAMERA_V2_POSE_GATE_DEVICE="${CAMERA_V2_POSE_GATE_DEVICE:-cpu}"
export CAMERA_V2_POSE_GATE_IMGSZ="${CAMERA_V2_POSE_GATE_IMGSZ:-224}"
export CAMERA_V2_POSE_GATE_THREADS="${CAMERA_V2_POSE_GATE_THREADS:-1}"
export CAMERA_V2_POSE_GATE_MIN_CONF="${CAMERA_V2_POSE_GATE_MIN_CONF:-0.08}"
export CAMERA_V2_POSE_GATE_STRONG_CONF="${CAMERA_V2_POSE_GATE_STRONG_CONF:-0.30}"
export CAMERA_V2_POSE_GATE_FALLBACK_CONF="${CAMERA_V2_POSE_GATE_FALLBACK_CONF:-0.22}"
export CAMERA_V2_POSE_GATE_MODEL_CONF="${CAMERA_V2_POSE_GATE_MODEL_CONF:-0.03}"
export CAMERA_V2_POSE_GATE_MAX_CANDIDATES="${CAMERA_V2_POSE_GATE_MAX_CANDIDATES:-2}"
export CAMERA_V2_POSE_GATE_TIMEOUT_SEC="${CAMERA_V2_POSE_GATE_TIMEOUT_SEC:-0.55}"
export CAMERA_V2_POSE_GATE_PADDING="${CAMERA_V2_POSE_GATE_PADDING:-0.14}"
export CAMERA_V2_POSE_GATE_POSITIVE_TTL_SEC="${CAMERA_V2_POSE_GATE_POSITIVE_TTL_SEC:-12}"
export CAMERA_V2_POSE_GATE_NEGATIVE_TTL_SEC=0
export CAMERA_V2_POSE_GATE_SOFT_KEEP_CONF="${CAMERA_V2_POSE_GATE_SOFT_KEEP_CONF:-0.14}"
export CAMERA_V2_POSE_GATE_REJECT_HITS="${CAMERA_V2_POSE_GATE_REJECT_HITS:-2}"
export CAMERA_V2_POSE_GATE_REJECT_WINDOW_SEC="${CAMERA_V2_POSE_GATE_REJECT_WINDOW_SEC:-10}"

export CAMERA_V2_RES_CAPTURE_CAMERAS="${CAMERA_V2_RES_CAPTURE_CAMERAS:-CAM-01,CAM-02,CAM-04,CAM-05}"
export CAMERA_V2_RES_CAPTURE_WIDTH="${CAMERA_V2_RES_CAPTURE_WIDTH:-1920}"
export CAMERA_V2_RES_CAPTURE_HEIGHT="${CAMERA_V2_RES_CAPTURE_HEIGHT:-1080}"
export CAMERA_V2_RES_CAPTURE_DIR="${CAMERA_V2_RES_CAPTURE_DIR:-$ROOT/.runtime/yolo26_resolution}"

export CAMERA_V2_TRT86_PYTHON="${CAMERA_V2_TRT86_PYTHON:-$ROOT/.venv-trt86/bin/python}"
export CAMERA_V2_TRT86_ENGINE="${CAMERA_V2_TRT86_ENGINE:-$ROOT/artifacts/yolo26s_trt86/yolo26s-672x384-b1-fp32-trt86.engine}"
export CAMERA_V2_TRT86_SHM_WORKER="${CAMERA_V2_TRT86_SHM_WORKER:-$ROOT/scripts/yolo26_trt86_shm_worker_v3.py}"

fail() { printf 'CAMERA_RES_CAPTURE_PREFLIGHT ERROR: %s\n' "$*" >&2; exit 1; }
[[ -x "$CAMERA_V2_TRT86_PYTHON" ]] || fail "TRT86 python missing: $CAMERA_V2_TRT86_PYTHON"
[[ -s "$CAMERA_V2_TRT86_ENGINE" ]] || fail "TRT86 engine missing: $CAMERA_V2_TRT86_ENGINE"

MAIN_PYTHON=""
for candidate in "${CAMERA_V2_MAIN_PYTHON:-}" "$ROOT/.venv/bin/python" "$(command -v python3 2>/dev/null || true)"; do
  [[ -n "$candidate" && -x "$candidate" ]] || continue
  if "$candidate" - <<'PY' >/dev/null 2>&1
import gi
gi.require_version("Gst", "1.0")
from gi.repository import Gst  # noqa: F401
import numpy, yaml, dotenv, torch, ultralytics  # noqa: F401
import services.camera_v2.detection_resolution_capture  # noqa: F401
PY
  then MAIN_PYTHON="$candidate"; break; fi
done
[[ -n "$MAIN_PYTHON" ]] || fail "no Python can import resolution capture runtime"

rm -rf "$CAMERA_V2_RES_CAPTURE_DIR"
mkdir -p "$CAMERA_V2_RES_CAPTURE_DIR"

printf '%s\n' \
  "CAMERA_RES_CAPTURE source=source-tee one-shot=1 preconvert-gate=1" \
  "CAMERA_RES_CAPTURE targets=$CAMERA_V2_RES_CAPTURE_CAMERAS frame=${CAMERA_V2_RES_CAPTURE_WIDTH}x${CAMERA_V2_RES_CAPTURE_HEIGHT}" \
  "CAMERA_RES_CAPTURE output=$CAMERA_V2_RES_CAPTURE_DIR"

exec "$MAIN_PYTHON" -u -m services.camera_v2.detection_resolution_capture
